# Generated by Django 3.1.12 on 2025-09-12 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('summary', models.TextField()),
                ('sentiment', models.CharField(max_length=50)),
                ('topics', models.JSONField(default=list)),
                ('published_date', models.DateTimeField(null=True)),
            ],
        ),
    ]
